config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "openinfos#index"
  resources :openinfos

  resources :users do
  	resources :openinfos
    resources :resumeitems
    resources :downloads
    resources :corporates
  end	
  
  resource :session

  resources :viewers

  resource :viewersession

  resources :infocats

  resources :resumeitems

  resources :downloads

  resources :corporates

end

app/models/resumeitem.rb
class Resumeitem < ActiveRecord::Base
	belongs_to :user
	validates :sections, presence: true 
	validates :detail, presence: true
	validates :itemorder, presence: true, uniqueness: true
	

 

	
end

app/controllers/resumeitems_controller.rb
class ResumeitemsController < ApplicationController
	def index
		if current_viewer?
		@resumeitemskey = Resumeitem.where(:sections => "Key").order("itemorder")
		@resumeitemsexp = Resumeitem.where(:sections => "Experience").order("itemorder")
		@resumeitemsedu = Resumeitem.where(:sections => "Education").order("itemorder")
		@resumeitemsoth = Resumeitem.where(:sections => "Other").order("itemorder")
		@viewer = current_viewer
	elsif current_user?
		@resumeitemskey = Resumeitem.where(:sections => "Key").order("itemorder")
		@resumeitemsexp = Resumeitem.where(:sections => "Experience").order("itemorder")
		@resumeitemsedu = Resumeitem.where(:sections => "Education").order("itemorder")
		@resumeitemsoth = Resumeitem.where(:sections => "Other").order("itemorder")
		@user = current_user
	else
	redirect to root_path	
	end
 
	   
	end	

	def new
		require_user
		@user = current_user
		@resumeitem = @user.resumeitems.new
		
	end
	
	def create
		require_user
		@user = current_user
		@resumeitem = @user.resumeitems.new(resumeitem_params)
  	if @resumeitem.save
        flash[:success] = "Thanks for submitting"
        redirect_to resumeitems_path
    else
      flash[:error] = "Oops, try again."
  	 render :new
    end

	end

	def edit
		require_user
		@user = current_user
		@resumeitem = @user.resumeitems.find(params[:id])
	end	

	def update
		require_user
		@user = current_user
		@resumeitem = @user.resumeitems.find(params[:id])

		if @resumeitem.update(resumeitem_params)
        flash[:success] = "Information was updated"
        redirect_to resumeitems_path
    else
      flash[:error] = "Oops. There has been a problem, please retry."
      render :edit
    end
	end
		
	def destroy
		require_user
    	@user = current_user
    	@resumeitem = @user.resumeitems.find(params[:id])
    	@openinfo.destroy
    	flash[:success] = "This information was deleted succesfully"
    redirect_to resumeitems_path
	end	

	def show
		@resumeitem = Resumeitem.find(params[:id])
		@key = "Key"
		
	end	

private

	def resumeitem_params
		params.require(:resumeitem).permit(:sections, :organisation, :title_course, :location, :start_date, :end_date, :detail, :detail1, :detail2, :detail3, :detail4, :detail5, :detail6, :extradetail, :user_id, :itemorder, :Moreinformation)
	end


end

app/helpers/resumeitems_helper.rb
module ResumeitemsHelper
end

app/views/resumeitems/edit.html.erb
<div class="newopen" >
<h2>Edit CV Item</h2>


<%= simple_form_for [@user, @resumeitem], url: resumeitem_path, method: :put do |f| %>
	
	<h4>Section</h4><%= f.input :sections, collection: ["Key","Experience","Education","Other"], label: false %>
	<h4>Organisation</h4><%= f.input :organisation, label: false %>
	<h4>Job title or course attended</h4><%= f.input :title_course, label: false %>
	<h4>Location</h4><%= f.input :location, label: false %>
	<h4>Start Date</h4><%= f.input :start_date, label: false %>
	<h4>End Date</h4><%= f.input :end_date, label: false %>
	<h4>Bullet 1</h4><%= f.input :detail, label: false %>
	<h4>Bullet 2</h4><%= f.input :detail1, label: false %>
	<h4>Bullet 3</h4><%= f.input :detail2, label: false %>
	<h4>Bullet 4</h4><%= f.input :detail3, label: false %>
	<h4>Bullet 5</h4><%= f.input :detail4, label: false %>
	<h4>Bullet 6</h4><%= f.input :detail5, label: false %>
	<h4>Bullet 7</h4><%= f.input :detail6, label: false %>
	<h4>Item Order</h4><%= f.input :itemorder, label: false %>
	<h4>Detailed Information</h4><%= f.input :Moreinformation, label: false %>
 

	<%= f.button :submit, 'update CV Information' %>

<% end %> 
</div>

app/views/resumeitems/index.html.erb
<section class="Resume">	

<h2 id="resumehead" >CV/Resume</h2>

	<div class="createpublic">
		<% if current_user? %>
		<%= link_to "Create", new_resumeitem_path %>
		<% end %>
	</div>	

		<ul class="resumetabs">
			
			  
			  <li class="resumetab" id="resumetabakey"><a href="#" class="resumetaba" data-display1="block" ><h2>Key Points</h2></a></li>
			  <li class="resumetab" id="resumetabaexp"><a href="#" class="resumetaba" id="resumetabexp" data-display2="block"><h2>Experience</h2></a></li>
			  <li class="resumetab" id="resumetabaedu"><a href="#" class="resumetaba" id="resumetabedu" data-display3="block"><h2>Education</h2></a></li>
			  <li class="resumetab" id="resumetabaoth"><a href="#" class="resumetaba" id="resumetaboth" data-display4="block" ><h2>Other</h2></a></li>
			  </ul>
			  <ul id="resumekeygo" >

			 <% @resumeitemskey.each do |resumeitem| %>
				
					 
						
						
							<li><h4><%= resumeitem.detail %></h4>
							<% if resumeitem.Moreinformation.nil? %>
							</h4>
							<% elsif resumeitem.Moreinformation.empty? %>
							</h4>
							<%else%>
							<%= link_to "...", resumeitem_path(resumeitem.id) %></h4>
							<%end%>
							
							</li >
							<% if current_user? %><%= link_to "Edit", edit_resumeitem_path(resumeitem.id) %>
							<%= link_to "Delete", resumeitem_path(resumeitem.id), method: :delete %><% end %></li>
							
							
				
					
					
				<% end %> 
				</ul>

				

			
			
			
			<ul id="resumeexpb">
			
			
				<% @resumeitemsexp.each do |resumeitem| %>
				 
					<div class="expitem" >

							<li><h4><%= resumeitem.organisation %></h4></li>
							<h6><%= resumeitem.title_course %></h6>
							<h6 class="datesresume"><%= resumeitem.start_date %>-
							<%= resumeitem.end_date %></h6>
							<ul class="detailsexp">
							<li><%= resumeitem.detail %></li>
							<li><%= resumeitem.detail1 %></li>
							<li><%= resumeitem.detail2 %></li>
							<li><%= resumeitem.detail3 %></li>
							<li><%= resumeitem.detail4 %></li>
							<li><%= resumeitem.detail5 %></li>
							<li><%= resumeitem.detail6 %></li>
							<% if resumeitem.Moreinformation.nil? %>
							</h4>
							<% elsif resumeitem.Moreinformation.empty? %>
							</h4>
							<%else%>
							<%= link_to "...", resumeitem_path(resumeitem.id) %></h4>
							<%end%>
							
							</li>
							</ul>		
								
							<% if current_user? %>
							<div class="Editingopen" >	
							<h5><%= link_to "Edit", edit_resumeitem_path(resumeitem.id) %>
							<%= link_to "Delete", resumeitem_path(resumeitem.id), method: :delete %></h5>
							</div>
							<% end %>
							
						</div>
				
					
					
				<% end %> 
				</ul>


				

			
			
				<ul id="resumeedub">
				<% @resumeitemsedu.each do |resumeitem| %>
				
					
						<div class="expitem" >
						
							<li><h4><%= resumeitem.organisation %></h4></li>
							<h6><%= resumeitem.title_course %></h6>
							<h6 class="datesresume" ><%= resumeitem.start_date %>-
							<%= resumeitem.end_date %></h6>
							<ul class="detailsexp">
							<li><%= resumeitem.detail %></li>
							<li><%= resumeitem.detail1 %></li>
							<li><%= resumeitem.detail2 %></li>
							<li><%= resumeitem.detail3 %></li>
							<li><%= resumeitem.detail4 %></li>
							<li><%= resumeitem.detail5 %></li>
							<li><%= resumeitem.detail6 %></li>
							<% if resumeitem.Moreinformation.nil? %>
							</h4>
							<% elsif resumeitem.Moreinformation.empty? %>
							</h4>
							<%else%>
							<%= link_to "...", resumeitem_path(resumeitem.id) %></h4>
							<%end%>
							
							</li>
							</ul>
							<% if current_user? %>
							<div class="Editingopen" >	
							<h5><%= link_to "Edit", edit_resumeitem_path(resumeitem.id) %>
							<%= link_to "Delete", resumeitem_path(resumeitem.id), method: :delete %></h5>
							</div>
							<% end %>
							
					</div>
				
					
				<% end %> 
				</ul>
			

			
			
				<ul id="resumeothb">

				<% @resumeitemsoth.each do |resumeitem| %>
				
					
						
						
							<li><h4><%= resumeitem.organisation %></h4></li>
							<h6><%= resumeitem.title_course %></h6>
							<h6><%= resumeitem.start_date %></h6>
							<h6><%= resumeitem.end_date %></h6>
							<ul>
							<li><%= resumeitem.detail %></li>
							<li><%= resumeitem.detail1 %></li>
							<li><%= resumeitem.detail2 %></li>
							<li><%= resumeitem.detail3 %></li>
							<li><%= resumeitem.detail4 %></li>
							<li><%= resumeitem.detail5 %></li>
							<li><%= resumeitem.detail6 %></li>
						<% if resumeitem.Moreinformation.nil? %>
							</h4>
							<% elsif resumeitem.Moreinformation.empty? %>
							</h4>
							<%else%>
							<%= link_to "...", resumeitem_path(resumeitem.id) %></h4>
							<%end%>
							
							</li>
							</ul>
							<% if current_user? %>
							<div class="Editingopen" >	
							<h5><%= link_to "Edit", edit_resumeitem_path(resumeitem.id) %>
							<%= link_to "Delete", resumeitem_path(resumeitem.id), method: :delete %></h5>
							</div>
							<% end %>
					
					
				<% end %> 
				</ul>

				
    

	</section>

	

app/views/resumeitems/new.html.erb
<div class="newopen" >
<h2>New CV Item</h2>

<%= simple_form_for [@user, @resumeitem], url: resumeitems_path, method: :post do |f| %>
	
	<h4>Section</h4><%= f.input :sections, collection: ["Key","Experience","Education","Other"], label: false %>
	<h4>Organisation</h4><%= f.input :organisation, label: false %>
	<h4>Job title or course attended</h4><%= f.input :title_course, label: false %>
	<h4>Location</h4><%= f.input :location, label: false %>
	<h4>Start Date</h4><%= f.input :start_date, label: false %>
	<h4>End Date</h4><%= f.input :end_date, label: false %>
	<h4>Bullet 1</h4><%= f.input :detail, label: false %>
	<h4>Bullet 2</h4><%= f.input :detail1, label: false %>
	<h4>Bullet 3</h4><%= f.input :detail2, label: false %>
	<h4>Bullet 4</h4><%= f.input :detail3, label: false %>
	<h4>Bullet 5</h4><%= f.input :detail4, label: false %>
	<h4>Bullet 6</h4><%= f.input :detail5, label: false %>
	<h4>Bullet 7</h4><%= f.input :detail6, label: false %>
	<h4>Item Order</h4><%= f.input :itemorder, label: false %>
	<h4>Detailed Information</h4><%= f.input :Moreinformation, label: false %>
 

	<%= f.button :submit, 'Submit new CV item' %>

<% end %> 

</div>

app/views/resumeitems/show.html.erb
							<h2><%= @resumeitem.sections %></h2>
							<%if @resumeitem.sections == @key %>
							<h3><%= @resumeitem.detail %></h3>
							<%else %>
							<h3><%= @resumeitem.organisation %></h3>
							<h3><%= @resumeitem.title_course %>
							<% end %>
							<p></p>
							<%= @resumeitem.Moreinformation %>


							<% if current_user? %>
							<div class="Editingopen">
							<%= link_to "Edit", edit_resumeitem_path(@resumeitem.id) %>
							<%= link_to "Delete", resumeitem_path(@resumeitem.id), method: :delete %>
							</div>
							<% else %>
							<p></p>
							<% end %>	
							<%= link_to "Return to List", resumeitems_path %>