config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "openinfos#index"
  resources :openinfos

  resources :users do
  	resources :openinfos
    resources :resumeitems
    resources :downloads
    resources :corporates
  end	
  
  resource :session

  resources :viewers

  resource :viewersession

  resources :infocats

  resources :resumeitems

  resources :downloads

  resources :corporates

end

app/models/download.rb
class Download < ActiveRecord::Base
	has_attached_file :docupload,
		:url => "/documents/:hash.:extension",
		:hash_secret => "longSecretString",
		:path =>"/documents/:hash.:extension",
		:storage => :s3,
		:s3_credentials => Proc.new {|a| a.instance.s3_credentials }


	validates_attachment :docupload, content_type: { content_type: [ "application/msword" , "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.ms-excel" , "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/pdf" ]}
	
	belongs_to :user

	def s3_credentials
		{ :access_key_id => "AKIAIVNBXKTNNXTMJZNQ",
:secret_access_key => "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",
:bucket => "m356p748w857a" }
	end	


end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
	def index
	  if current_viewer?
	   @downloads = Download.where(:ViewerAllowed => true).order('itemorder')
	   @viewer = current_viewer
	  
	   elsif current_user?
	   @downloads = Download.order('itemorder')
	   @user = current_user
	
	   else
	   redirect_to root
	 end
	end   
 
	def new
		require_user
		@user = current_user
		@download = @user.downloads.new
	end
	
	def create
		require_user
		@user = current_user
		@download = @user.downloads.new(download_params)
		@download.save
		redirect_to downloads_path
	end

	def show
		@download = Download.find(params[:id])
		@downloadpath = @download.docupload.path
		@downloadurl = @downloadpath.insert(0, "https://s3.amazonaws.com/m356p748w857a")
		data = open(@downloadurl)
		send_data data.read, filename: @download.docupload_file_name, disposition: 'inline', stream: 'true', buffer_size: '4096'
		#send_file(@downloadurl)
		
	end	

	def edit
		require_user
		@user = current_user
		@download = @user.downloads.find(params[:id])
	end	

	def update
		require_user
		@user = current_user
		@download = @user.downloads.find(params[:id])

		if @download.update(download_params)
        flash[:success] = "Information was updated"
        redirect_to download_path(@download.id)
    else
      flash[:error] = "Oops. There has been a problem, please retry."
      render :edit
    end
  end  


    def destroy
    	require_user
    	@user = current_user
    	@download = @user.downloads.find(params[:id])
    	@download.destroy
    	flash[:success] = "This information was deleted succesfully"
    redirect_to downloads_path
    end	

    private

    def download_params
    	params.require(:download).permit(:title, :description, :user_id, :itemorder, :routing, :docupload, :ViewerAllowed)
    end	
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/views/downloads/edit.html.erb
<div class="newopen" >
<h2>Edit the document</h2>

<%= simple_form_for [@user, @download], url: download_path, method: :put do |f| %>

	<h4>Title</h4><%= f.input :title, label: false %>
	<h4>Description</h4><%= f.input :description, label: false %>
	<h4>Item Order</h4><%= f.input :itemorder, label: false %>
	<h4><%= @download.docupload_file_name%></h4><%= f.input :docupload, label: false %>
	
	
	<%= f.button :submit, "Edit Document" %>
	* Required field
<% end %>
</div>

app/views/downloads/index.html.erb
<div class="ichead" >

  <h2>Downloads</h2>
  <p></p> 
</div>
<section class="downloads">	
		
			<div class="createpublic" >
			<% if current_user? %>
			<%= link_to "Create", new_download_path %>
			<% end %>
			</div>

				<ul class="download"> 


			 <% @downloads.each_with_index do |download, index| %>
				
					
							<li><h2><%= link_to(download_path(download.id)) do %><%= image_tag "document-icon.png" %><% end %>
							
							<%= download.title %> </h2>
							<h5><%= download.description %><h5>
							</li>
							
							
							<% if current_user?%>
							<li><%= download.docupload.path %></li>
							
							<%end%>
							
							<% if current_user? %>
							<div class="Editingopen">
							<h5><%= link_to "Edit", edit_download_path(download.id) %>
							    <a href = "#" class="dochid" id=<%="downdel"+index.to_s%>  >Delete</a></h5>
							   <div class="behid" id = <%="downdelhid"+index.to_s%> >
							      <h5><%= link_to "Yes", download_path(download.id), method: :delete %></h5>
							      <h5><a href = "#" class="dochid2" id=<%="hiddowndel"+index.to_s%>  >No</a></h5>
							   </div>
							</div>
							
							<% end %>	
				<hr>
							
				<% end %> 

					</ul>
			

					
	</section>

app/views/downloads/new.html.erb
<div class="newopen" >
<h2>Upload a new document</h2>

<%= simple_form_for [@user, @download], url: downloads_path, method: :post do |f| %>

	<h4>Title</h4><%= f.input :title, label: false %>
	<h4>Description</h4><%= f.input :description, label: false %>
	<h4>Item Order</h4><%= f.input :itemorder, label: false %>
	<h4>Document Location</h4><%= f.input :docupload, label: false %>
	<h4>Viewer can see?</h4><%= f.input :ViewerAllowed, label: false %>
	
	
	
	<%= f.button :submit, "Add document" %>
	* Required field
<% end %>

</div>

app/views/downloads/show.html.erb
<% redirect_to downloads_path %>