config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "openinfos#index"
  resources :openinfos

  resources :users do
  	resources :openinfos
    resources :resumeitems
    resources :downloads
    resources :corporates
  end	
  
  resource :session

  resources :viewers

  resource :viewersession

  resources :infocats

  resources :resumeitems

  resources :downloads

  resources :corporates

end

app/models/openinfo.rb
class Openinfo < ActiveRecord::Base
	validates :title, presence: true
	validates :Openinformation, presence: true
	validates :itemorder, presence: true, uniqueness: true
	belongs_to :user
end

app/controllers/openinfos_controller.rb
class OpeninfosController < ApplicationController
	def index
	  
	   @openinfos = Openinfo.all.order('itemorder')
	   @user = 0
	end   
 
	def new
		require_user
		@user = current_user
		@openinfo = @user.openinfos.new
	end
	
	def create
		require_user
		@user = current_user
		@openinfo = @user.openinfos.new(openinfo_params)
		@openinfo.save
		redirect_to openinfos_path
	end

	def show
		@openinfo = Openinfo.find(params[:id])
	end	

	def edit
		require_user
		@user = current_user
		@openinfo = @user.openinfos.find(params[:id])
	end	

	def update
		require_user
		@user = current_user
		@openinfo = @user.openinfos.find(params[:id])

		if @openinfo.update(openinfo_params)
        flash[:success] = "Information was updated"
        redirect_to openinfos_path(@openinfo.id)
    else
      flash[:error] = "Oops. There has been a problem, please retry."
      render :edit
    end
  end  
    def destroy
    	require_user
    	@user = current_user
    	@openinfo = @user.openinfos.find(params[:id])
    	@openinfo.destroy
    	flash[:success] = "This information was deleted succesfully"
    redirect_to openinfos_path
    end	

    private
    def openinfo_params
    	params.require(:openinfo).permit(:title, :Openinformation, :user_id, :itemorder, :Moreinformation)
    end	

end

app/helpers/openinfos_helper.rb
module OpeninfosHelper
end

app/views/openinfos/edit.html.erb
<div class="newopen" >
<h2>Edit Pubic Item</h2>

<%= simple_form_for [@user, @openinfo], url: openinfo_path, method: :put do |f| %>

	<h4>Title</h4><%= f.input :title, label: false %>
	<h4>Detail</h4><%= f.input :Openinformation, label: false %>
	<h4>Item Order</h4><%= f.input :itemorder, label: false %>
	<h4>More Information for Show page</h4><%= f.input :Moreinformation, label: false %>
	
	<%= f.button :submit, "Edit information" %>
	* Required field
<% end %>
</div>

app/views/openinfos/index.html.erb
<div class="oihead" >

  <h2>Selection of posts</h2>
  <p></p> 
</div>
<section class="openinformations">	
		
			<div class="createpublic" >
			<% if current_user? %>
			<%= link_to "Create", new_openinfo_path %>
			<% end %>
			</div>

			 <% @openinfos.each do |openinfo| %>
				
					<div class="openinformation">
						
						
							<h2><%= openinfo.title %></h2>
							<h5><%= openinfo.Openinformation %>
							<% if openinfo.Moreinformation.empty? %>
							</h5>
							<% else %>
										<%= link_to "....more.", openinfo_path(openinfo.id) %></h5>
							<% end %>
							<% if current_user? %>
							<div class="Editingopen">
							<h5><%= link_to "Edit", edit_openinfo_path(openinfo.id) %><%= link_to "Delete", openinfo_path(openinfo.id), method: :delete %></h5>
							</div>
							
							<% end %>	
				
					</div>
					
				<% end %> 

			

					
	</section>

app/views/openinfos/new.html.erb
<div class="newopen" >
<h2>New Pubic Item</h2>

<%= simple_form_for [@user, @openinfo], url: openinfos_path, method: :post do |f| %>

	<h4>Title</h4><%= f.input :title, label: false %>
	<h4>Detail</h4><%= f.input :Openinformation, label: false %>
	<h4>Item Order</h4><%= f.input :itemorder, label: false %>
	<h4>More Information for Show page</h4><%= f.input :Moreinformation, label: false %>
	
	
	<%= f.button :submit, "Add information" %>
	* Required field
<% end %>
</div>

app/views/openinfos/show.html.erb
							

							<h2><%= @openinfo.title %></h2>
							<p><%= @openinfo.Openinformation %></p>
							<p></p>
							<%= @openinfo.Moreinformation %>
							<% if current_user? %>
							<div class="Editingopen">
							<%= link_to "Edit", edit_openinfo_path(@openinfo.id) %>
							<%= link_to "Delete", openinfo_path(@openinfo.id), method: :delete %>
							</div>
							<% else %>
							<p></p>
							<% end %>	
							<%= link_to "Return to List", openinfos_path %>