config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "openinfos#index"
  resources :openinfos

  resources :users do
  	resources :openinfos
    resources :resumeitems
    resources :downloads
    resources :corporates
  end	
  
  resource :session

  resources :viewers

  resource :viewersession

  resources :infocats

  resources :resumeitems

  resources :downloads

  resources :corporates

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/corporate.rb
class Corporate < ActiveRecord::Base
	has_attached_file :corpimage,
	:url => "/images/:hash.:extension",
		:hash_secret => "longSecretString",
		:path =>"/images/:hash.:extension",
		:storage => :s3,
		:s3_credentials => Proc.new {|a| a.instance.s3_credentials }

	validates_attachment_content_type :corpimage, :content_type => /\Aimage\/.*\Z/

	has_attached_file :logoimage,
	:url => "/images/:hash.:extension",
		:hash_secret => "longSecretString",
		:path =>"/images/:hash.:extension",
		:storage => :s3,
		:s3_credentials => Proc.new {|a| a.instance.s3_credentials }

	validates_attachment_content_type :logoimage, :content_type => /\Aimage\/.*\Z/

	belongs_to :user
	validates :name, presence: true, uniqueness: true
	validates :address, presence: true, uniqueness: true

	geocoded_by :address
	before_validation :geocode

	def country_name
    country = Country[country_code]
    country.translations[I18n.locale.to_s] || country.name
  end

  def self.search(query)
  	
  where("name like ? or sector like ?", "%#{query}%", "%#{query}") 

	 


	end

	def s3_credentials
		{ :access_key_id => "AKIAIVNBXKTNNXTMJZNQ",
:secret_access_key => "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",
:bucket => "m356p748w857a" }
	end	

end

app/models/download.rb
class Download < ActiveRecord::Base
	has_attached_file :docupload,
		:url => "/documents/:hash.:extension",
		:hash_secret => "longSecretString",
		:path =>"/documents/:hash.:extension",
		:storage => :s3,
		:s3_credentials => Proc.new {|a| a.instance.s3_credentials }


	validates_attachment :docupload, content_type: { content_type: [ "application/msword" , "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.ms-excel" , "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/pdf" ]}
	
	belongs_to :user

	def s3_credentials
		{ :access_key_id => "AKIAIVNBXKTNNXTMJZNQ",
:secret_access_key => "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",
:bucket => "m356p748w857a" }
	end	


end

app/models/infocat.rb
class Infocat < ActiveRecord::Base
	validates :title, presence: true
	validates :brief_description, presence: true
	validates :itemorder, presence: true, uniqueness: true
	validates :routing, presence: true
	belongs_to :user
end

app/models/openinfo.rb
class Openinfo < ActiveRecord::Base
	validates :title, presence: true
	validates :Openinformation, presence: true
	validates :itemorder, presence: true, uniqueness: true
	belongs_to :user
end

app/models/resumeitem.rb
class Resumeitem < ActiveRecord::Base
	belongs_to :user
	validates :sections, presence: true 
	validates :detail, presence: true
	validates :itemorder, presence: true, uniqueness: true
	

 

	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :username, presence: true, uniqueness: true
	validates :email, presence: true, uniqueness: true
	validates :password, presence: true, confirmation: true, length: {minimum: 8}
	has_many :openinfos
	has_many :resumeitems
	has_many :infocats
	has_many :downloads
	has_many :corporates
end

app/models/viewer.rb
class Viewer < ActiveRecord::Base
	has_secure_password
	validates :username, presence: true, uniqueness: true
	validates :email, presence: true, uniqueness: true
	validates :password, presence: true, confirmation: true, length: {minimum: 8}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
        flash[:success] = "Thanks for signing up! Now please log in."
        redirect_to root_path
    else
      flash[:error] = "Oops, try again."
  	 render :new
    end
  end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end
		
end

app/controllers/viewers_controller.rb
class ViewersController < ApplicationController
		def new
  	require_user
  	@viewer = Viewer.new
  end

  def create
  	require_user
  	@viewer = Viewer.new(user_params)
  	if @viewer.save
        flash[:success] = "New Viewer created."
        redirect_to root_path
    else
      flash[:error] = "Oops, try again."
  	 render :new
    end
  end

	private

	def user_params
		params.require(:viewer).permit(:username, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corporates_helper.rb
module CorporatesHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/infocats_helper.rb
module InfocatsHelper
end

app/helpers/openinfos_helper.rb
module OpeninfosHelper
end

app/helpers/resumeitems_helper.rb
module ResumeitemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/viewers_helper.rb
module ViewersHelper
end

app/helpers/viewersessions_helper.rb
module ViewersessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>Access to extra information - mpwa.me</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  
  <%= csrf_meta_tags %>
  
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta charset="utf-8" />

		
  
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
	
	
	
	<!--[if lt IE 9]>
    		<script src="js/html5shiv.js"></script>
    		<script src="js/respond.min.js"></script>
  <![endif]-->

  <style>[touch-action="none"]{ -ms-touch-action: none; touch-action: none; }[touch-action="pan-x"]{ -ms-touch-action: pan-x; touch-action: pan-x; }[touch-action="pan-y"]{ -ms-touch-action: pan-y; touch-action: pan-y; }[touch-action="scroll"],[touch-action="pan-x pan-y"],[touch-action="pan-y pan-x"]{ -ms-touch-action: pan-x pan-y; touch-action: pan-x pan-y; }
  </style>

  <style id="style-1-cropbar-clipper">/* Copyright 2014 Evernote Corporation. All rights reserved. */
      .en-markup-crop-options {
          top: 18px !important;
          left: 50% !important;
          margin-left: -90px !important;
          width: 180px !important;
          border: 2px rgba(255,255,255,.38) solid !important;
          border-radius: 4px !important;
      }

      .en-markup-crop-options div div:first-of-type {
          margin-left: 0px !important;
      }
  </style>

		<!--<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55331302-1', 'auto');
  ga('send', 'pageview');

</script>-->
</head>
<body >
		
 
		<div class="page" >
      <section id="section1" class="setofdata">
          <div class="slowscroll" id="slowscroll1" >

       <div id="brandingcontainer" >
        
          <h2>Mark Artherton, CFA</h2>
          <h4>Emerging Market Equity</h4>
          <h4>Strategist, Stock Selector, Portfolio Constructor</h4>
          
      </div>       

        <div class="usercontainer" >      
           <div class="usertype">
              <% if current_viewer? %>
                  <p></p>
                   <h4>User: <%= current_viewer.username %></h4>
              <% elsif current_user? %>
                    <p></p>
                   <h4>Admin logged in: <%= current_user.username %></h4>
              <% else %>
                  <div class="login" >
                  <%= simple_form_for :viewersession, url: viewersession_path do |f| %>
                  <h4>User name</h4>
                  <%= f.input :username, label: false, required: false %>
                  <h4>Password</h4>
                  <%= f.input :password, label: false, required: false %>

                  <%= f.button :submit, 'Log in' %>
                  <% end %>
                  </div>
              <% end %>
            </div>
        </div>    

      

            

      <div id="sicontainer" >
        <ul id="sinav" >
          <li><a href="https://twitter.com/mark_emerging" ><h3  >a</h3></a></li>
          <li><a href="https://www.linkedin.com/pub/mark-artherton/47/40/7a4" ><h3  >j</h3></a></li>
          <li><a href="https://www.flickr.com/photos/127492516@N02/" ><h3  >v</h3></a></li>
          <li><a href="https://www.youtube.com/channel/UC4W96gmcG_XDCwQLpDLdvig" ><h3  >r</h3></a></li>
        </ul>
    </div>

    <div id="container" >
      <div class="txtdes" >
        <h2 >Private Area</h2>
      </div>
    </div>
    


  <div id="navcontainer" >
    <ul id="navul" >
      <li><a href="http://www.mpwa.me" class="centfloat" ><h3  >Home</h3></a></li>
      <li><a href="http://www.mpwa.me/links/links.html" class="centfloat" ><h3 >Links</h3></a></li>
      <li><a href="http://www.blog.mpwa.me" class="centfloat" ><h3  >Blog</h3></a></li>
          
      <% if current_viewer? | current_user? %>
       <li  class="privatenav" >
        <h3  ><%= link_to "Private", openinfos_path %></h3>
        </li>
       <li  class="privatenav2" id="drophidden" ><h3 ><%= link_to "Categories", infocats_path %></h3></li>

       
        
       

      <% end %>

      <% if current_viewer? %>
      
      <li  class="privatenav2" >
        <h3 ><%= link_to "Log out", viewersession_path, method: :delete %></h3>
        </li>
        <li><h3>
        <% flash.each do |key, value| %>
             <div class="flashcontainer" >
              <div class="flash <%= key %>"><%= value %></div>
              </div>
              <% end %>
       </h3></li>   
        </ul>
      <% elsif current_user? %>
        
        <li  class="privatenav2" >
        <h3  ><%= link_to "Log out", session_path, method: :delete %></h3>
        </li>  
        <li   >
        <h3 class="privatenav2" ><%= link_to "Create new viewer", new_viewer_path %></h3>
        </li>
        <li><h3>
        <% flash.each do |key, value| %>
             <div class="flashcontainer" >
              <div class="flash <%= key %>"><%= value %></div>
              </div>
              <% end %>
       </h3></li>   
        </ul>
      <% else %>
        <li><h3>
        <% flash.each do |key, value| %>
             <div class="flashcontainer" >
              <div class="flash <%= key %>"><%= value %></div>
              </div>
              <% end %>
       </h3></li>   
        </ul>
        
      
      <% end %>  
    
  </div>
    <div id="hidcontain" >        
      <ul id ="hiddendrop">
              <% @infocats = Infocat.all.order('itemorder') %>
             <% @infocats.each do |infocat| %>
              <li  >
              <h3><%= link_to infocat.title, [infocat.routing] %> </h3>
              </li>
              <% end %>
          </ul>
     </div>     

</section>  
<section id="section1" >
  <div  id="slowscroll2" >
		<%= yield %>
  </div>  
</section>
			<div class="footer" Role="footer">
				<p></p>
				<small>Mark Artherton, CFA. In Emerging Market Equity since 1998.  &copy; Mark Artherton. Created and programmed by Mark Artherton. All Rights reserved</small>
				<p></p>
				<small>contact email: info@mpwa.me</small>
			</div>		
    </div>  
		
	</body>
</html>